### PR TITLE
Fix bug handle empty mappings when removing mapping types

### LINKED ISSUE #1177: [BUG] Running the solution is getting null error in metadata migration
### What is the bug?
After running the snapshot command, and waiting till completion, ive ran the command for metadata evaluate and got an null error

### How can one reproduce the bug?
making a snapshot from ES_6.7 and then try to get metadata evaluated

### What is the expected behavior?
A normal migration from ES_6.7 to OS_2.17

### What is your host/environment?
ES_6.7 to OS_2.17

### Do you have any screenshots?
image
image
image

### PR DESCRIPTION
**Pull request by peternied**
### Description
Fix bug handle empty mappings when removing mapping types

### Issues Resolved
- Resolves #1177

### Check List
- [X] New functionality includes testing
  - [X] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java [hunk 1]
```diff
@@ -38,8 +38,16 @@ public GlobalMetadata transformGlobalMetadata(GlobalMetadata globalData) {
             templatesRoot.fields().forEachRemaining(template -> {
                 var templateCopy = (ObjectNode) template.getValue().deepCopy();
                 var indexTemplate = (Index) () -> templateCopy;
-                transformIndex(indexTemplate, IndexType.TEMPLATE);
-                templates.set(template.getKey(), indexTemplate.getRawJson());
+                try {
+                    transformIndex(indexTemplate, IndexType.TEMPLATE);
+                    templates.set(template.getKey(), indexTemplate.getRawJson());
+                }  catch (Exception e) {
+                    log.atError()
```
Comment (lewijacn) [inline RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java:45]: Do we currently populate anything in the summary to say a transformation didn't work?

**Review by lewijacn — APPROVED** [review]

File: RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java (hunk 1 above)
Comment (peternied) [reply RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java:45]: Good callout - Nope, any items that are 'rejected' in this way will never show up in the UX (So at least there wouldn't be a false positive)

We will need to reorganize the data processing model to handle this cases :(
