### PR TITLE
vpc subnet selection support

### LINKED ISSUE #1430: [BUG] Unable to create Fargate service when deploying migration assistant
### What is the bug?
After working around the issue mentioned here (https://github.com/opensearch-project/opensearch-migrations/issues/1423) , I'm getting the following error when trying to deploy migration assistant
```
OSMigrations-dev-us-west-2-ReindexFromSnapshot | 4:30:46 PM | CREATE_FAILED        | AWS::ECS::Service                                   | reindexFromSnapshotStack/ServiceFargateService/Service (ServiceFargateService44B4DE75) Resource handler returned message: "Invalid request provided: subnets can have at most 16 items. (Service: Ecs, Status Code: 400, Request ID: <request_id>) (SDK Attempt Count: 1)" (RequestToken: <request_token>, HandlerErrorCode: InvalidRequest)
OSMigrations-dev-us-west-2-MigrationConsole | 4:32:08 PM | CREATE_FAILED        | AWS::ECS::Service                                   | migration-console/ServiceFargateService/Service (ServiceFargateService44B4DE75) Resource handler returned message: "Invalid request provided: subnets can have at most 16 items. (Service: Ecs, Status Code: 400, Request ID: <request_id>) (SDK Attempt Count: 1)" (RequestToken: <request_token>, HandlerErrorCode: InvalidRequest)
❌  OSMigrations-dev-us-west-2-MigrationConsole failed: _ToolkitError: The stack named OSMigrations-dev-us-west-2-MigrationConsole failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: subnets can have at most 16 items. (Service: Ecs, Status Code: 400, Request ID: <request_id>) (SDK Attempt Count: 1)" (RequestToken: <request_token>, HandlerErrorCode: InvalidRequest)

```

### What are your migration environments?
Elasticsearch 7.17
Opensearch 2.17 

### How can one reproduce the bug?
- Configure backfill migration settings inside of cdk.context.json like outlined on this page (https://opensearch.org/docs/latest/migration-assistant/deploying-migration-assistant/configuration-options/#backfill-migration-using-rfs)
- Remove     "artifactBucketRemovalPolicy": "DESTROY" parameter to bypass lambda creation
- Run ` cdk deploy "*" --c contextId=backfill-migration --require-approval never --concurrency 3`

### What is the expected behavior?
Migration assistant ecs cluster spins up without issues.

### Do you have any additional context?
I had to bypass the lambda creation for reindex-from-snapshot since my company has a source control policy that prohibits lambdas without vpcs to be created.
In addition, the vpc being used also has more than 16 subnets.

### PR DESCRIPTION
**Pull request by jugal-chauhan**
### Description
This PR adds support for users to specify both a VPC ID and specific subnet IDs when deploying Migration Assistant into an existing VPC. Previously, when users provided a VPC ID, all subnets in that VPC were used automatically. This enhancement gives users more control over subnet selection.

### Issues Resolved
- Resolves #1430
- Resolves [MIGRATIONS-2472](https://opensearch.atlassian.net/browse/MIGRATIONS-2472) 

### Check List
- [x] New functionality includes testing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts [hunk 1]
```diff
@@ -39,62 +38,6 @@ export interface MigrationStackProps extends StackPropsExt {
...
-                subnetFilters: [
-                    SubnetFilter.byIds(desiredSubnetIds)
-                ]
-            })
-        }
-        else {
-            throw new Error(`Not enough AZs available for private subnets in VPC to meet desired ${azCount} AZs. The AZ count can be specified with the 'mskAZCount' context option`)
-        }
-    }
-
```
Comment (lewijacn) [inline deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts:97]:
```
    validateMSKOptions(vpcDetails: VPCDetails,  brokerNodeCount: number) {
        const numSubnets = vpcDetails.subnetSelection.subnets?.length
        if (numSubnets !== 2 && numSubnets !== 3) {
            throw new Error(`MSK requires 2 or 3 subnets each with a unique AZ, but have detected ${numSubnets} subnets provided`)
        }
        if (brokerNodeCount < 2 || brokerNodeCount % numSubnets !== 0) {
            throw new Error(`The MSK broker node count (${brokerNodeCount} nodes inferred) must be a multiple of the number of 
                    AZs (${numSubnets} AZs inferred). The node count can be set with the 'mskBrokersPerAZCount' context option.`)
        }
    }
```

I think replacing with something simpler like this will still provide value, while removing the subnet selecting logic we no longer need

**Review by jugal-chauhan — COMMENTED** [review]
I approve of these changes. 
I performed a deployment test using CDK with custom subnets (each from a different AZ, and having the same subnetType). Deployment was successful. Having not met the requirements results in an error (as expected, with a clear message to the user)
